let restorentData = [
    {
        id: "34r7774",
        name: "Varalakshmi Tiffins",
        cloudinaryImageId: "8523266de1213e8ea57e5df4eedf747e",
        locality: "Manikonda",
        areaName: "Narsingi",
        costForTwo: "₹150 for two",
        cuisines: ["South Indian", "North Indian", "Thandoori"],
        avgRating: 4.5,
        veg: true,
        type: "Noth"
     },
     {
     id: "34773e74",
     name: "Udipi;s upgaar",
     cloudinaryImageId: "nqgrpd6e8vliz57mxlvu ",
     locality: "GAchibowlli",
     areaName: "Narsingi",
     costForTwo: "₹550 for two",
     cuisines: ["South Indian", "North Indian"],
     avgRating: 4.5,
     veg: true,
  },
     {
     id: "3437774",
     name: "ChaiPoint",
     cloudinaryImageId: "p4znxkstyrdobxwl6rxa ",
     locality: "Ameerpet",
     areaName: "Narsingi",
     costForTwo: "₹50 for two",
     cuisines: ["South Indian", "North Indian"],
     avgRating: 3.5,
     veg: true,
  },
  {
    id: "3437774",
    name: "Eat Fit",
    cloudinaryImageId: "6126c9b45de2cb222405c1af8a321e74 ",
    locality: "Kukatpalli",
    areaName: "Narsingi",
    costForTwo: "₹560 for two",
    cuisines: ["South Indian", "North Indian"],
    avgRating: 2.5,
    veg: true,
 },
 {
    id: "3477374",
    name: "SubWay",
    cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b ",
    locality: "Kukatpalli",
    areaName: "Narsingi",
    costForTwo: "₹560 for two",
    cuisines: ["South Indian", "North Indian"],
    avgRating: 5.5,
    veg: true,
 },
 {
    id: "347773",
    name: "ChaiPoint",
    cloudinaryImageId: "p4znxkstyrdobxwl6rxa ",
    locality: "Ameerpet",
    areaName: "Narsingi",
    costForTwo: "₹50 for two",
    cuisines: ["South Indian", "North Indian"],
    avgRating: 3.5,
    veg: true,
 }
    ];

export default restorentData;